name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  checkout:
    name: codeCehckOut
    runs-on: ubuntu-latest
    steps: #code checkout. and prepare environment (node install)
      - uses: actions/checkout@v3
  init:
    name: initializeSetup
    needs: ["checkout"]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
  test:
    name: runTests
    needs: ["init"]
    steps:
      - run: npm test #run tests
  imageBuildAndPush:
    name: buildImageAndPush
    needs: ["test"]
    steps:
      - name: Login to Docker Hub #make image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push #push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: slokesh/node-github-actions:latest
